server:
  port: 8085 # 设置端口

spring: # 配置数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_system?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jackson:
    time-zone: Asia/Shanghai # 设置时区
  devtools:
    restart:
      enabled: true  # 设置开启热部署
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml 
  type-aliases-package: com.student.system.model